name: Trigger AWX Job

on:
  push:
    branches:
      - master  # Adjust the branch as needed

jobs:
  trigger-awx-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger AWX Job
        env:
          AWX_API_URL: 'http://192.168.10.4/api/v2'  # Replace with your AWX server URL
          AWX_TEMPLATE_ID: '9'            # Replace with the ID of your AWX job template
          AWX_JOB_LIMIT: '5'                             # Replace with the number of jobs to trigger
        run: |
          curl -k -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.AWX_API_TOKEN }}" \
               "$AWX_API_URL/job_templates/$AWX_TEMPLATE_ID/launch/" \
               -d '{"limit": "$AWX_JOB_LIMIT"}'
